### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/jupyterlab-myst#141]
The following features

## Fundamental Roadblocks to Use

- [x] Style is the same as Jupyter
- [x] Trusted model is the same as Jupyter
- [ ] Styles don't leak to other packages
- [ ] Can render inline HTML
- [ ] Uses the styles for existing `alert-info` etc.
- [ ] Test with other extensions (e.g. deck, holoviews)
- [ ] A pass on performance improvements (e.g. double render)

## Bugs 

- [ ] see 0.2.0 milestone?

## Citation support

This is the first cross-document linking we introduce.

- [ ] Can add DOIs
- [ ] Can add citations from bibtex files
- [ ] Adds a references section at the bottom

### Can render Markdown files in Jupyter

- [ ] Open up markdown files and render as MyST

## Documentation

- [ ] Improve/add user documentation beyond readme
- [x] Host on myst-tools.org/docs/jupyterlab
- [ ] Have a repository of example notebooks to show features
    - [ ] Maybe this is just the docs?
    - [ ] Helpful as a stand-alone repository, but maybe those notebooks are just automated and copied out?
- [ ] Page on how to integrate this to your hub

**Comment by stevejpurves** [comment]
@agoose77 I was transferring some of the note from the hackmd that some planning went into a few months back. Feel free to edit the issue text directly.

**Comment by fperez** [comment]
Hi folks! Just landing back to work after JupyterCon (was off for a week) - it was wonderful to catch up in person, despite sadly missing @rowanc1 (I hope you're feeling better!).

Quick q - the first thing I did upon opening my home machine was to do a mamba refresh of my packages, being particularly interested in testing the new JupyterLab 4.0.0 we discussed at the conference.

But I just saw that for some reason, jlab-myst 1.2.0 is incompatible with JLab 4.0, it asks me to downgrade to 3.6:

```
  Package            Version  Build         Channel                  Size
───────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────

  + jupyterlab-myst    1.2.0  pyhd8ed1ab_0  conda-forge/noarch     Cached

  Downgrade:
───────────────────────────────────────────────────────────────────────────

  - jupyterlab         4.0.0  pyhd8ed1ab_1  conda-forge
  + jupyterlab         3.6.3  pyhd8ed1ab_0  conda-forge/noarch     Cached
```

Is this something easily fixable with a point release, or does it require "real work" and thus a job for the 0.2.0 milestone (which BTW I'm confused numbers-wise, as I see 0.2.0 as a future milestone but 1.2.0 is already out, but I'm sure that's just me being out of the loop :)

Thanks all for the great work!

**Comment by agoose77** [comment]
Yes, we made a 1.0 release a while ago!
4.0 changes a lot of notebook related frustrés, so its not been a trivial job to port to 4.0. It's in the pipeline, but will take a bit of time!

**Comment by fperez** [comment]
Understood, thx! LMK if I can be of any help with testing/feedback!

**Comment by rowanc1** [comment]
We have released the first part of these changes as v2.0.0, which now supports juptyerlab 4. Would love some wider testing help, as there were some major under the hood changes! Next up are citations!

**Comment by fperez** [comment]
Congratulations and huge thanks team for the great work!! I just installed the 2.0.0 final, will be playing with it over the next few days and will continue providing feedback. 🥂 🎉 🚀
