### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by nthiery** [executablebooks/jupyterlab-myst#58]
### Context

For course material in French, we are using extensively Jupyter notebooks
in Myst-Markdown, rendered in JupyterLab for interactive use and Jupyter-Book
for browsing on the web. Myst features like admonitions are great to structure
the content; now that they are available in JupyterLab, we will start using them
extensively.

There remains one caveat:
```
:::{warning} ...
...
:::
```

is rendered in JupyterLab with an English title "Warning" instead of the
desirable "Avertissement" displayed in Jupyter-Book.

### Proposal

It would be desirable for  the rendering of myst features to use the language of the document.

Caveat: define "the language of the document"

- In the context of a jupyter book, it would be consistent to use the language
  set in the jupyter book configuration.
- If nothing else: using the language of the JupyterLab interface?

### Tasks and updates

- [ ] enable internationalization
- [ ] reuse existing translations (e.g. from JupyterBook and its dependencies)
- [ ] define a logic for setting the language
- [ ] implement that logic

**Comment by nthiery** [comment]
Quick discussion here https://github.com/orgs/executablebooks/discussions/912#discussioncomment-4651002
Happy to help with the beta testing.

**Comment by chrisjsewell** [comment]
https://github.com/executablebooks/myst-spec/issues/52
